"""
Django settings for mtbs_backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env
load_dotenv(BASE_DIR / '.env')

# True while `manage.py test` is running. Used only to switch off rate limiting,
# which otherwise leaks between test methods (the throttle counter lives in the
# process-wide cache, so test order would start deciding pass/fail).
TESTING = 'test' in sys.argv


def env_flag(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=()):
    raw = os.environ.get(name)
    if not raw:
        return list(default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# The key signs sessions and JWTs, so a published one lets anyone mint a token
# for any account. It comes from the environment in production; the fallback
# exists so a fresh clone runs without setup and is only reachable with DEBUG on.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# Debug tracebacks print settings and SQL to anyone who triggers an error.
DEBUG = env_flag('DJANGO_DEBUG', default=not SECRET_KEY)

if not SECRET_KEY:
    if not DEBUG:
        raise RuntimeError(
            'DJANGO_SECRET_KEY must be set when DEBUG is off. Generate one with:\n'
            '  python -c "from django.core.management.utils import '
            'get_random_secret_key as k; print(k())"'
        )

# Empty ALLOWED_HOSTS with DEBUG off rejects every request, so give production a
# clear knob and development the loopback names it actually uses.
ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    default=['localhost', '127.0.0.1', '[::1]'] if DEBUG else [],
)


# Application definition

INSTALLED_APPS = [
    # Must precede staticfiles: it swaps `runserver` for an ASGI server so
    # WebSockets work in development without a separate process.
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'movies',
    'accounts',
    'theatres',
    'showtimes',
    'bookings',
    'payments',
    'analytics',
    'reviews',
    'watchlist',
    'wallet',
    'rest_framework',
    'corsheaders',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = env_list(
    'DJANGO_CORS_ORIGINS',
    default=['http://localhost:3000'],  # React default port
)

# The auth tokens travel as cookies now, and a browser discards Set-Cookie on a
# cross-origin response unless the server opts in here (and the client sends
# `withCredentials`). Note this also forbids a wildcard Allow-Origin, which is
# why CORS_ALLOWED_ORIGINS above must stay an explicit list.
CORS_ALLOW_CREDENTIALS = True

# Django rejects any unsafe request whose Origin header isn't listed here. The
# React dev server is a different origin from the API, so it needs naming even
# though the two are the same *site*.
CSRF_TRUSTED_ORIGINS = env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    default=CORS_ALLOWED_ORIGINS,
)

# --- Auth cookies ---------------------------------------------------------
# Both JWTs live in httpOnly cookies so that no script on the page can read
# them. See accounts/cookies.py for the flags and accounts/authentication.py
# for the CSRF check that this arrangement makes mandatory.
AUTH_COOKIE_ACCESS = 'mtbs_access'
AUTH_COOKIE_REFRESH = 'mtbs_refresh'
AUTH_COOKIE_ACCESS_PATH = '/api/'
# Scoped to the only endpoint that consumes it, so the long-lived credential
# isn't attached to every ordinary API call.
AUTH_COOKIE_REFRESH_PATH = '/api/token/refresh/'

# 'Lax' is right whenever the frontend and API share a registrable domain —
# cookies ignore the port, so localhost:3000 and localhost:8000 already count
# as the same site in development. A production split across *different*
# domains would need 'None' (plus HTTPS), which browsers increasingly block as
# a third-party cookie; serving both under one domain avoids that entirely.
AUTH_COOKIE_SAMESITE = os.environ.get('DJANGO_AUTH_COOKIE_SAMESITE', 'Lax')

# Must stay readable by JavaScript: axios copies this cookie into the
# X-CSRFToken header on every write. Setting CSRF_COOKIE_HTTPONLY = True looks
# like hardening and instead breaks every POST in the app with a bare 403.
CSRF_COOKIE_HTTPONLY = False

# Nothing needed in development: cookies ignore ports, so the csrftoken this
# server sets on `localhost` is already readable by the React app on
# localhost:3000. If production splits the two across subdomains
# (app.example.com / api.example.com), this cookie becomes host-only to the API
# and the frontend can no longer read it — set DJANGO_CSRF_COOKIE_DOMAIN to
# '.example.com' there so both subdomains share it.
CSRF_COOKIE_DOMAIN = os.environ.get('DJANGO_CSRF_COOKIE_DOMAIN') or None

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


ROOT_URLCONF = 'mtbs_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mtbs_backend.wsgi.application'
ASGI_APPLICATION = 'mtbs_backend.asgi.application'

# Channel layer: how one request's broadcast reaches sockets held elsewhere.
#
# In-memory is the default because a single `runserver`/`daphne` process holds
# every socket, so there is nothing to cross — and it means no Redis to install.
# It does NOT span processes: the moment you run more than one worker, set
# REDIS_URL (and `pip install channels-redis`) or broadcasts will only reach the
# clients that happen to share a process with the booking request.
REDIS_URL = os.environ.get('REDIS_URL')
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'}
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



NEON_DB_STRING = os.getenv("NEON_DB_STRING")

if not NEON_DB_STRING:
    raise RuntimeError(
        "NEON_DB_STRING is not configured. Django will not start without the Neon database."
    )

DATABASES = {
    "default": dj_database_url.parse(
        NEON_DB_STRING,
        conn_max_age=600,
        conn_health_checks=True,
    )
}


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    # Reads the JWT from an httpOnly cookie rather than an Authorization
    # header, and enforces CSRF on writes because a cookie is sent
    # automatically where a header never was.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.CookieJWTAuthentication',
    ],
    # Paginated by default. Without this, `/api/movies/` grows without bound and
    # every client pays for the whole catalogue on first paint. Clients read
    # `results`; `?page_size=` lets a caller ask for more, up to the cap.
    'DEFAULT_PAGINATION_CLASS': 'mtbs_backend.pagination.StandardPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('THROTTLE_ANON', '120/min'),
        'user': os.environ.get('THROTTLE_USER', '600/min'),
        # Login and registration are the endpoints worth guessing at, so they
        # get their own much tighter budget via ScopedRateThrottle.
        'auth': os.environ.get('THROTTLE_AUTH', '10/min'),
        # The gate scanner. Tighter than `user` because it takes a ticket
        # reference and says whether it's real — unthrottled, that's an
        # enumeration oracle no matter how large the keyspace is.
        'verify': os.environ.get('THROTTLE_VERIFY', '60/min'),
    },
}

if TESTING:
    # See the TESTING note at the top: shared throttle state makes tests
    # order-dependent, and rate limiting isn't what any of them are asserting.
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = []
    # The auth views name `throttle_classes` explicitly, so emptying the
    # default list above doesn't reach them — the rate itself has to be None.
    # `accounts.tests` turns it back on for the two tests that assert on it.
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        'anon': None, 'user': None, 'auth': None, 'verify': None,
    }

# Throttle counters and the filter-options cache live here. LocMem is per
# process, which is fine for one server; point CACHE_URL at Redis to share it.
CACHE_URL = os.environ.get('CACHE_URL')
if CACHE_URL:
    CACHES = {'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': CACHE_URL,
    }}
else:
    CACHES = {'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'mtbs-default',
    }}

# How long the movie filter dropdowns may be stale. They change only when an
# admin edits the catalogue, and every write invalidates them anyway.
FILTER_OPTIONS_CACHE_SECONDS = int(os.environ.get('FILTER_OPTIONS_CACHE_SECONDS', 300))



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTH_USER_MODEL = 'accounts.CustomUser'  # Should match exactly



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Production hardening -------------------------------------------------
# Off in development because HTTPS redirects and secure-only cookies break
# http://localhost. `manage.py check --deploy` covers the rest.
if not DEBUG:
    SECURE_SSL_REDIRECT = env_flag('DJANGO_SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Tell browsers to keep using HTTPS. Starts at an hour so a misconfigured
    # deploy is recoverable; raise it once the certificate is settled.
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', 3600))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    # Behind a reverse proxy Django only sees plain HTTP, so it needs the
    # header the proxy sets to know the original request was secure.
    if env_flag('DJANGO_BEHIND_PROXY'):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # The browsable API is a debugging aid; in production it invites poking.
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] = [
        'rest_framework.renderers.JSONRenderer',
    ]
