# Generated by Django 5.2.1 on 2026-08-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
