# Generated by Django 5.2.1 on 2026-08-03 21:05

from django.db import migrations


def backfill_seats(apps, schema_editor):
    """Give pre-existing bookings concrete seat numbers.

    Older bookings only recorded a count (num_seats), so we hand out seat
    numbers sequentially per showtime — earliest booking gets the lowest
    seats. This keeps the seat map consistent with what was already sold.
    """
    Booking = apps.get_model('bookings', 'Booking')
    Showtime = apps.get_model('showtimes', 'Showtime')

    for showtime in Showtime.objects.all():
        next_seat = 1
        bookings = (
            Booking.objects
            .filter(showtime=showtime)
            .exclude(status='CANCELLED')
            .order_by('created_at', 'id')
        )
        for booking in bookings:
            if booking.seats:  # already has real seats, leave it alone
                next_seat = max(next_seat, max(booking.seats) + 1)
                continue
            count = booking.num_seats or 0
            booking.seats = list(range(next_seat, next_seat + count))
            next_seat += count
            booking.save(update_fields=['seats'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_seats'),
    ]

    operations = [
        migrations.RunPython(backfill_seats, noop),
    ]
