# Generated by Django 5.2.1 on 2026-08-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Awaiting payment'), ('ACTIVE', 'Active'), ('REDEEMED', 'Redeemed')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='GiftCardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('method', models.CharField(choices=[('CARD', 'Card'), ('UPI', 'UPI')], default='CARD', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gift_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='wallet.giftcard')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['status', 'timestamp'], name='wallet_gift_status_15d77a_idx')],
            },
        ),
    ]
