# Generated by Django 5.2.1 on 2026-08-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_status',
            field=models.CharField(choices=[('NONE', 'No refund'), ('PENDING', 'Refund processing'), ('REFUNDED', 'Refunded')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
