# Generated by Django 5.2.1 on 2026-08-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_bookings_bo_user_id_6151bb_idx_and_more'),
        ('payments', '0002_payment_refund_amount_payment_refund_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'timestamp'], name='payments_pa_status_38b377_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-timestamp'], name='payments_pa_timesta_931e2d_idx'),
        ),
    ]
