# Generated by Django 5.2.1 on 2026-08-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_payments_pa_status_38b377_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CARD', 'Card'), ('WALLET', 'Wallet')], default='CARD', max_length=10),
        ),
    ]
