# Generated by Django 5.2.1 on 2026-08-03 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0001_initial'),
        ('theatres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='theatre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='theatres.theatre'),
        ),
    ]
