# Generated by Django 5.2.1 on 2026-08-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimes', '0002_showtime_theatre'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Ticket price per seat', max_digits=8),
        ),
    ]
