# Generated by Django 5.2.1 on 2026-08-04 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_options_movie_duration_minutes_and_more'),
        ('showtimes', '0003_showtime_price'),
        ('theatres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='end_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='rows',
            field=models.PositiveIntegerField(default=5, help_text='Number of seat rows (max 26, labelled A-Z)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(26)]),
        ),
        migrations.AddField(
            model_name='showtime',
            name='screen_number',
            field=models.PositiveIntegerField(default=1, help_text='Which screen inside the theatre this show occupies', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='showtime',
            name='seats_per_row',
            field=models.PositiveIntegerField(default=10, help_text='Seats in each row', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['theatre', 'screen_number', 'start_time'], name='showtimes_s_theatre_c3966f_idx'),
        ),
    ]
