# Generated by Django 5.2.1 on 2026-08-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_movies_movi_title_652549_idx'),
        ('showtimes', '0004_showtime_end_time_showtime_rows_and_more'),
        ('theatres', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['start_time'], name='showtimes_s_start_t_2f568a_idx'),
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['movie', 'start_time'], name='showtimes_s_movie_i_274781_idx'),
        ),
    ]
