# Generated by Django 5.2.1 on 2026-08-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='accounts_cu_role_666d59_idx'),
        ),
    ]
