# Generated by Django 5.2.1 on 2026-08-04 17:36
#
# Choices only — `choices` is validation metadata, not schema, so this touches
# no data and existing USER/ADMIN rows are unaffected. It exists so the
# migration state matches the model and `makemigrations --check` stays clean.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_accounts_cu_role_666d59_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('STAFF', 'Ticket Staff'), ('ADMIN', 'Admin')], default='USER', max_length=10),
        ),
    ]
